### ISSUE TITLE
∇softmax modifies input argument

### ISSUE THREAD

**Issue by jondeuce** [FluxML/NNlib.jl#264] opened 2021-01-01 00:03 UTC
In a fresh environment, the following bug persists:

```
import NNlib, CUDA

julia> x = CUDA.ones(3,3); # before
julia> Δ = CUDA.ones(3,3);
julia> NNlib.∇softmax(Δ, x);
julia> x # after
3×3 CUDA.CuArray{Float32,2}:
 0.333333  0.333333  0.333333
 0.333333  0.333333  0.333333
 0.333333  0.333333  0.333333
```

Environment:
```
julia> Pkg.status()
Status `~/Documents/code/nnlib-bug.jl/Project.toml`
  [052768ef] CUDA v2.3.0
  [872c559c] NNlib v0.7.9

julia> versioninfo()
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 9 3950X 16-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, znver2)
Environment:
  JULIA_CUDA_USE_BINARYBUILDER = false
  JULIA_NUM_THREADS = 36
```

**Comment by jondeuce** [comment] 2021-01-01 00:32
FWIW, this bug does not occur on the cpu

**Comment by jondeuce** [comment] 2021-01-01 04:15
Update: the same issue occurs for all of `softmax`, `∇softmax`, `logsoftmax`, and `∇logsoftmax`, and apparently is due to `CUDA.jl` where an [issue has already been filed](https://github.com/JuliaGPU/CUDA.jl/issues/592). This issue can probably be closed, if somebody more familiar with the internals can verify my conclusion.

**Comment by ToucheSir** [comment] 2021-01-01 20:37
I believe https://github.com/FluxML/NNlib.jl/pull/250 fixes this (in tandem with that CUDA.jl PR).

**Comment by jondeuce** [comment] 2021-01-01 20:54
Yes, the [CUDA.jl PR](https://github.com/JuliaGPU/CUDA.jl/pull/523) seems to be exactly what I'm looking for (and much more...)

**Comment by CarloLucibello** [comment] 2021-01-07 08:37
Last NNlib tag will bypass CUDA.jl overload due to the changed gradient API. 
it will fall back to the general implementation here also for CuArrays,
so you should see the bug fixed if using NNlib v0.7.10

**Comment by jeremiedb** [comment] 2021-01-09 23:59
@CarloLucibello I'm not sure if this issue should be closed. On both v0.7.10 and v0.7.11, `softmax` is still modifying its inputs: 

```
using CUDA
using NNlib

julia> x1 = CUDA.rand(3)
3-element CuArray{Float32,1}:
 0.32975423
 0.14462776
 0.466419

julia> softmax(x1)
3-element CuArray{Float32,1}:
 0.33585864
 0.27909827
 0.38504308

julia> x1
3-element CuArray{Float32,1}:
 0.33585864
 0.27909827
 0.38504308
```

**Comment by CarloLucibello** [comment] 2021-01-10 00:12
I forgot that the problem is not only with the gradient but with softmax itself

**Comment by CarloLucibello** [comment] 2021-01-10 00:15
maybe this problem is serious enough that it deserves a hotfix in CUDA.jl, instead of waiting for https://github.com/JuliaGPU/CUDA.jl/pull/523 (which probably will land on julia 1.6 only)

**Comment by CarloLucibello** [comment] 2021-06-11 06:31
fixed in NNlibCUDA

**Closed by CarloLucibello** 2021-06-11 06:31 UTC
